name: UDSPlugin
main: com.undeadscythes.udsplugin.UDSPlugin
version: 2.49.4
description: UDSPlugin for CB 1.6.2-R0.1 (2838).
author: UndeadScythes - daveyognaut2@gmail.com
website: http://undeadscythes.webs.com/
depend: []
softdepend: []
commands:
  A:
  AcceptRules:
  Admin:
  Afk:
  Back:
  Ban:
  Bounty:
    aliases: bounties
  Broadcast:
    aliases: b
  Butcher:
  C:
  Call:
  Challenge:
  Chat:
  Check:
  Chunk:
  Ci:
  City:
  Clan:
  Day:
  Debug:
  DelWarp:
  Demote:
  Enchant:
  Face:
  Gift:
  God:
  Heal:
  Help:
  Home:
  I:
    aliases: item
  Ignore:
  InvSee:
  Jail:
  Kick:
  Kit:
  Lockdown:
  Map:
  Me:
  Mod:
  Money:
  N:
  Nick:
  Night:
  P:
  Password:
  PayBail:
  Pet:
  Plot:
  Portal:
  Powertool:
  Private:
  Promote:
  Pvp:
  R:
    aliases: reply
  Rain:
  Region:
  Rules:
  Scuba:
  Server:
  SetWarp:
  Shop:
  Signs:
  Sit:
  Spawn:
  Spawner:
  Stack:
  Stats:
  Storm:
  Sun:
  Tell:
    aliases: [whisper, msg]
  Ticket:
  TGM:
    aliases: [gm, gamemode]
  TP:
  UnBan:
  UnJail:
  Vanish:
  VIP:
  Warden:
  Warp:
    aliases: warps
  WE:
  Where:
  Who:
    aliases: list
  WhoIs:
  World:
  XP:
    aliases: exp
  Y:
