name: UDSPlugin1
main: com.undeadscythes.udsplugin.UDSPlugin
version: 0.1
description: UDSlugin1 for CB 1.4.2-R0.2 #2449.
author: UndeadScythes - daveyognaut2@gmail.com
website: http://undeadscythes.webs.com/
depend: []
softdepend: []
commands:
  a:
  acceptrules:
  back:
  ban:
  blind:
  bounty:
    aliases: bounties
  broadcast:
    aliases: b
  butcher:
  c:
  call:
  challenge:
  check:
  ci:
  city:
  clan:
  day:
  delwarp:
  demote:
  enchant:
  face:
  firework:
  gift:
  god:
  heal:
  help:
  home:
  i:
    aliases: item
  ignore:
  invsee:
  jail:
  kick:
  kit:
  lockdown:
  map:
  mapdupe:
  me:
  money:
  n:
  nick:
  night:
  ownerme:
  p:
  paybail:
  pet:
  powertool:
  private:
  promote:
  r:
    aliases: reply
  rain:
  region:
  resetquarry:
  rules:
  scuba:
  server:
  serverinfo:
  setspawn:
  setwarp:
  shop:
  signs:
  sit:
  spawn:
  spawner:
  stack:
  stats:
  storm:
  sun:
  swearjar:
  tell:
    aliases: [whisper, msg]
  tgm:
    aliases: [gm, gamemode]
  ticket:
  timereset:
  tp:
  udsreload:
  unban:
  unjail:
  unnick:
  vip:
  warp:
    aliases: warps
  we:
  where:
  who:
    aliases: list
  whois:
  xp:
    aliases: exp
  y:
