name: UDSPlugin
main: com.undeadscythes.udsplugin.UDSPlugin
version: 2.30
description: UDSPlugin1 for CB 1.6.2-R0.1 (2815).
author: UndeadScythes - daveyognaut2@gmail.com
website: http://undeadscythes.webs.com/
depend: []
softdepend: []
commands:
  a:
  acceptrules:
  admin:
  afk:
  back:
  ban:
  bounty:
    aliases: bounties
  broadcast:
    aliases: b
  butcher:
  c:
  call:
  challenge:
  check:
  chunk:
  ci:
  city:
  clan:
  day:
  debug:
  delwarp:
  demote:
  enchant:
  face:
  gift:
  god:
  heal:
  help:
  home:
  i:
    aliases: item
  ignore:
  invsee:
  jail:
  kick:
  kit:
  lockdown:
  map:
  me:
  mod:
  money:
  n:
  nick:
  night:
  p:
  paybail:
  pet:
  portal:
  powertool:
  private:
  promote:
  r:
    aliases: reply
  rain:
  region:
  rules:
  scuba:
  server:
  setspawn:
  setwarp:
  shop:
  signs:
  sit:
  spawn:
  spawner:
  stack:
  stats:
  storm:
  sun:
  tell:
    aliases: [whisper, msg]
  ticket:
  tgm:
    aliases: [gm, gamemode]
  tp:
  unban:
  unjail:
  vanish:
  vip:
  warden:
  warp:
    aliases: warps
  we:
  where:
  who:
    aliases: list
  whois:
  world:
  xp:
    aliases: exp
  y:
